apiVersion: v1
kind: Secret
metadata:
  name: tinyllama
  namespace: ai-models
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/display-name: "TinyLlama 1.1B Chat ModelCar"
stringData:
  URI: oci://quay.io/redhat-ai-services/modelcar-catalog:tinyllama-1.1b-chat-v1.0
type: Opaque
