apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  annotations:
    opendatahub.io/connections: tinyllama
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: tinyllama
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/genai-asset: "true"
  name: tinyllama
  namespace: ai-models
spec:
  model:
    uri: oci://quay.io/redhat-ai-services/modelcar-catalog:tinyllama-1.1b-chat-v1.0
  replicas: 1
  template:
    containers:
    - name: main
      args:
      - --dtype=half
      - --max-model-len=2048
      - --gpu-memory-utilization=0.45
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
  router:
    gateway:
      refs:
      - name: maas-default-gateway
        namespace: openshift-ingress
    route: {}
    scheduler: {}
